### ISSUE TITLE
Question on extra info that is returned for expression evaluation

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/scala-debug-adapter#108]
Firstly, fantastic job on everything so far with the expression evaluation. It's been really cool to play around with this and continually see it improve. Playing around tonight with the newest things I have a couple questions on when more information is returned vs when the value is just returned. To give an example:

_This just simply returns the value_
```
 dap> 3
  3
```

_Whereas this returns a whole bunch of other stuff_
```
 dap> "hi"
  "hi"
    CASE_INSENSITIVE_ORDER: String$CaseInsensitiveComparator@2211
    COMPACT_STRINGS: true
    LATIN1: 0
    UTF16: 1
    coder: 0
    hash: 0
    serialPersistentFields: ObjectStreamField[0]@2212
    serialVersionUID: -6849794470754667710
    value: byte[2]@2339
 ```

Maybe a naive question, but why does 3 just return 3 here but "hi" returns all the extra stuff? None of it really seems that useful for the output of the evaluation, so I'm curious if any of this is even needed to be shown to the user in the panel? wdyt?

**Comment by tgodzik** [comment]
I think this is just all the accessible fields of a String instance, while 3 is just treated as a primitive.

**Comment by ckipp01** [comment]
ahh ok ok, that makes sense.

```
 dap> opt
  Some@870 "Some(test)"
    serialVersionUID (Option): -114498752079829388
    serialVersionUID (Some): 1234815782226070388
    value: "test"
```
So then would the goal be in the evaluator window to always show all this info? If so, I'll just close this.

**Comment by tgodzik** [comment]
It shows all the fields without hiding it, I think for anyone that is doing an actual debugging this is needed and we should not hide anything. There is also the `toString` value shown next to it, which should be enough if you don't want to delve deeper into the object.

**Comment by ckipp01** [comment]
> It shows all the fields without hiding it, I think for anyone that is doing an actual debugging this is needed and we should not hide anything. There is also the `toString` value shown next to it, which should be enough if you don't want to delve deeper into the object.

Cool, thanks for explaining. I'm a println debugger, can you tell 😀

**Comment by tgodzik** [comment]
> > It shows all the fields without hiding it, I think for anyone that is doing an actual debugging this is needed and we should not hide anything. There is also the `toString` value shown next to it, which should be enough if you don't want to delve deeper into the object.
> 
> Cool, thanks for explaining. I'm a println debugger, can you tell grinning

Me too recently :smile:

**Comment by ckipp01** [comment]
> Just my two cents: this behavior is handled by [microsoft/java-debug ](https://github.com/microsoft/java-debug) library that we are using for debugging. On our side, we need to evaluate an expression and return [JDI](https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/) value, such as `IntegerValue`, `StringReference`, `ObjectReference`, etc. So to alter that behavior we would need to modify `java-debug` library, which of course is possible but I'm not sure if reasonable. Also, [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) seems to be deliberately designed to support the possibility to show child variables. And besides all that, it depends on a client how it's shown, e.g. in VSCode it's hidden by default:
> 
> ![Screenshot from 2021-09-30 14-04-37](https://user-images.githubusercontent.com/6402694/135452077-25550a1a-cb61-42d1-b680-6f4865b9ec09.png) ![Screenshot from 2021-09-30 14-04-49](https://user-images.githubusercontent.com/6402694/135452078-78799170-e2f0-419d-a2a9-a01b8f294c5b.png)

Thanks for the context @tdudzik, all the debugging stuff is quite new to me, so it's helpful. Also, thanks for the screenshot. Seeing how they hide it, I'll try to see if [nvim-dap](https://github.com/mfussenegger/nvim-dap) can do something similiar, since that's the app most Neovim users will be using.

**Comment by tdudzik** [comment]
No problem, feel free to ask if you have any questions. And thank you for testing and creating issues, it's really helpful!
