### ISSUE TITLE
Cannot evaluate a method inside of itself if the method is `@tailrec`

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#118]
From @vincenzobaz 

```scala
object Main extends App {
  @scala.annotation.tailrec
  def f(x: Int): Int = {
    if (x <= 42) {
1=>x
    } else f(x*2)
  }

  f(2)
}
```
if I evaluate the expression `x` it works.
If I evaluate `f(x)`: `Cannot evaluate because of ch.epfl.scala.debugadapter.internal.evaluator.ExpressionCompilationFailed: could not optimize @tailrec annotated method f: it contains a recursive call not in tail position.`

The solution could be to remove the `@tailrec` annotation on top of `f`. That is not a problem since the class that contains `f` will not be re-class loaded: the original `f` will be evaluated.

**Comment by tgodzik** [comment]
I will take a look, should be a case of just removing the tailrec annotation.
