### ISSUE TITLE
Cannot evaluate when classpath is too big (> 30k characters)

### ISSUE THREAD

**Issue by andyczerwonka** [scalacenter/scala-debug-adapter#148]
**Metals:** v0.10.8
**Editor:** vscode
**Build Server:** Bloop v1.4.10-8-8d1cbc4f 

When I try and use the expression evaluator that was recently updated in v0.10.8, it fails for me with:

`Cannot evaluate because of ch.epfl.scala.debugadapter.internal.evaluator.ExpressionCompilationFailed: object scala in compiler mirror not found..`

I was doing some spelunking with @tgodzik, and I threw in a `println` in the test to pull out the `classpath`.
```scala
println(s"Classpath -> ${System.getProperty("java.class.path")}")
``` 
The result of that is `/tmp/jvm-forker-manifest7987195697692046528.jar`

Given Bloop uses a separate classpath and always forks the JVM process for tests, could that be what is causing this not to work for me?

**Comment by adpi2** [comment]
Thanks @andyczerwonka for opening this. At first I was surprised by this `/tmp/jvm-forker-manifest-xx.jar` file. I looked at the [code in Bloop](https://github.com/scalacenter/bloop/blob/34cd16174384e82fdb9bccf8d2b4f7e46ba2471b/frontend/src/main/scala/bloop/exec/JvmProcessForker.scala#L123-L139) and it seems Bloop creates this file when the classpath is too big and exceeds the maximum command size on Windows. I will try to reproduce that and see if that could be the cause of the bug.

**Comment by andyczerwonka** [comment]
> Bloop creates this file when the classpath is too big and exceeds the maximum command size on Windows. I will try to reproduce that and see if that could be the cause of the bug.

@adpi2, I’m on Linux, Ubuntu 20.04.

**Comment by adpi2** [comment]
I confirm that the size of the classpath is the root cause of the problem. I was able to reproduce on Ubuntu and the [fix](https://github.com/scalacenter/scala-debug-adapter/pull/150) is ready to be reviewed.

**Comment by nhvtgd** [comment]
Enter the same error when trying to evaluate expression on vscode using metals. I'm on mac. My class path is `/var/folders/sg/vr4x0_bx5tl0gdvbttcbv6qw0000gp/T/jvm-forker-manifest1627181751509981460.jar`
