### ISSUE TITLE
Cannot attach debugger to the process

### ISSUE THREAD

**Issue by kpodsiad** [scalacenter/scala-debug-adapter#206]
When running Metals server with the `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=localhost:5022` it is possible to attach debugger to the remote JVM. It works when `Bloop` is a build server but it doesn't work for `sbt`. I don't know if this bug is specific to the Metals or if it happens in other projects as well.

Attach debugger configuration specified in `launch.json`:
```
{
  "version": "0.2.0",
  "configurations": [
    // Attach debugger when running via:
    // `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=localhost:5022`
    {
      "type": "scala",
      "request": "attach",
      "name": "Attach debugger",
      // name of the module that is being debugging
      "buildTarget": "metals",
      // Host of the jvm to connect to
      "hostName": "localhost",
      // Port to connect to
      "port": 5022
    }
  ]
}
```

Metals server sends to the server:
```
[Trace - 00:25:19 pm] Sending request 'debugSession/start - (21)'
Params: {
  "targets": [
    {
      "uri": "file:/Users/kpodsiadlo/vl/metals/#metals/Compile"
    }
  ],
  "dataKind": "scala-attach-remote",
  "data": {}
}
```
but gets in response:
```
[Trace - 00:25:19 pm] Received response 'debugSession/start - (21)' in 9ms
Result: null
Error: {
  "code": -33000,
  "message": ""
}
```

I'll try to investigate this problem a bit more, but for now, I'm creating an issue to not forget about it.

**Comment by adpi2** [comment]
Thanks for reporting this. I'll try to reproduce it later this week.
