### ISSUE TITLE
Expression evaluation doesn't work with -Xsource:3

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/scala-debug-adapter#251]
As discussed in https://github.com/scalacenter/bloop/pull/1741 we might need to add `scalacOptions` field along to scalaVersion.

I can take a look at it next week.

**Comment by adpi2** [comment]
Thank you @tgodzik.

One important detail is that each build target can have its own set of `scalacOptions`, so maybe we should add `scalacOptions` into `ClassPathEntry`. For the library dependencies the `scalacOptions` are unknown, which is a problem: we might not be able to evaluate expressions into a source of a dependency. One way to solve this would be for sbt and other build tools to store the scalac options into the pom file when publishing it.

**Comment by tgodzik** [comment]
Or alternatively we could add -Xsource:3 option by default for the libraries?

**Comment by adpi2** [comment]
Yeah sure but `-Xsource:3` is only a part of the problem. We might also need to enable all experimental features or to add  `-Xsource:future`.

**Comment by tgodzik** [comment]
> Yeah sure but `-Xsource:3` is only a part of the problem. We might also need to enable all experimental features or to add `-Xsource:future`.

yeah, things like kind projector might also be problematic, so probably no solution for that unless libraries publish their options in pom.xml or MANIFEST :/
