### ISSUE TITLE
[Scala 3] expression evaluation doesn't evaluate

### ISSUE THREAD

**Issue by unthingable** [scalacenter/scala-debug-adapter#261]
When attempting to evaluate an expression while stopped at a breakpoint:

```
1+1
Cannot evaluate because of failed compilation:
-- Error: /var/folders/71/ynbmyt9d3nz_pqr93020rp7r0000gn/T/scala-debug-adapter-8b9d92d83c274012a52576709f7adac017798932612006910083/StepSequencer.scala:190:36 
190 |      state.keyScrollOffset = guardY(state.keyScrollOffset + (pageMul * inc))
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                              expression already inserted.
```
(the "already inserted" expression is the line at the stopped breakpoint)

Build server currently being used is Bloop v1.5.2.

Metals Java: 17.0.2 from Eclipse Adoptium

Metals Server version: 0.11.7

Scala 3.1.1

**Comment by unthingable** [comment]
I should add this happens very rarely, I can't even remember how to reproduce this. Most of the time it's still

```
1+1
Cannot evaluate because of ch.epfl.scala.debugadapter.internal.evaluator.MethodInvocationFailed: "java.lang.NoClassDefFoundError: scala/runtime/Nothing$".
```

**Comment by adpi2** [comment]
Thanks for opening the issue. I think I know how to fix the  `expression already inserted`.

The second error "java.lang.NoClassDefFoundError: scala/runtime/Nothing$" is unexpected. I would be curious to know how to reproduce this. Could you give more details?

**Comment by adpi2** [comment]
@unthingable I tried to reproduce the second error but with no success. There must be some problem with the classpath used by Bloop to start the debuggee. Could you share your repository or reproduce in another repository?

**Comment by unthingable** [comment]
@adpi2 so this one is a little weird to explain: the project in question is a Bitwig controller extension (https://github.com/unthingable/monsterjam - haven't published the new Scala3 version yet), that's built against a public API, available as interfaces only. The runtime is Bitwig's own JVM, which contains the API implementation. It doesn't contain Scala, instead I bundle the Scala runtime as a shadow dependency into the extension JAR.

When debugging it's not Bloop that starts the debuggee, the process is already running with an open remote debug port. I launch the debugger with a remote debug configuration:

```json
    "version": "0.2.0",
    "configurations": [
        {
            "type": "scala",
            "name": "Bitwig Debug (Attach)",
            // "projectName": "monsterjam",
            "buildTarget": "monsterjam",
            "request": "attach",
            "hostName": "localhost",
            "port": 9898
        }
    ]
```

Seems that the debugger is unable to locate the bundled and loaded Scala runtime.

Probably not reproducible without actually running Bitwig, but if anyone is up for it, there is a free trial version (https://www.bitwig.com/download/) and then `% BITWIG_DEBUG_PORT=9898 /Applications/Bitwig\ Studio\ 4.3.app/Contents/MacOS/BitwigStudio` :)

**Comment by adpi2** [comment]
Thanks for the details. It seems your process manages several class loaders and the expression evaluator does not know which one to use, so it picks one randomly, but not the right one. I think I can fix this by calling `getClass().getClassLoader()` on the current `this`.

**Comment by adpi2** [comment]
Actually if the scala lib is shaded then its package names are changed and the evaluator cannot load them any more. So I don't think there is a general solution to this problem. Shaded jars are not compatible with debuggers.

**Comment by unthingable** [comment]
> So I don't think there is a general solution to this problem. Shaded jars are not compatible with debuggers.

Thank you for looking into this. It seems there is at least one solution and IntelliJ has found it, but I don't know what it is.
