### ISSUE TITLE
Hot Code Replace

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#393]
Hot code replace is implemented in [microsoft/java-debug](https://github.com/microsoft/java-debug) as shown in the [documentation]( https://code.visualstudio.com/docs/java/java-debugging#_hot-code-replace)

Related issues:
- [Metals feature request](https://github.com/scalameta/metals-feature-requests/issues/336)
- [Issue in Bloop](https://github.com/scalacenter/bloop/issues/1242)

**Comment by adpi2** [comment]
@acodervic I agree with you, it is a cool and useful feature. Unfortunately I don't have time to look into it now.

If you want to take a look and contribute, I can give you some pointers:
- There is a [IHotCodeReplaceProvider](https://github.com/scalacenter/java-debug/blob/bdf8433cd446815b7a556571c30b78aada32a34c/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IHotCodeReplaceProvider.java) in java-debug that we need to implement in the `scala-debug-adapter`.
- We already have an implementation [here](https://github.com/scalacenter/scala-debug-adapter/blob/9e29f94f12ce335476e77d186f6b7ea0be226793/modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugAdapter.scala#L64-L79) but it does not do anything
- The Java implementation is [here](https://github.com/microsoft/java-debug/blob/a0e31fc8bda7dbe604ef94aabd769bfb0a26bbbc/com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java#L354:20), it would probably be possible to adapt it for Scala. The main difficulty lies in the fact that a Scala source file can generate many class files. If needed the SourceLookUpProvider can associate source files with class files and vice-versa.

**Comment by acodervic** [comment]
> @acodervic I agree with you, it is a cool and useful feature. Unfortunately I don't have time to look into it now.
> 
> If you want to take a look and contribute, I can give you some pointers:
> 
> * There is a [IHotCodeReplaceProvider](https://github.com/scalacenter/java-debug/blob/bdf8433cd446815b7a556571c30b78aada32a34c/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IHotCodeReplaceProvider.java) in java-debug that we need to implement in the `scala-debug-adapter`.
> * We already have an implementation [here](https://github.com/scalacenter/scala-debug-adapter/blob/9e29f94f12ce335476e77d186f6b7ea0be226793/modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugAdapter.scala#L64-L79) but it does not do anything
> * The Java implementation is [here](https://github.com/microsoft/java-debug/blob/a0e31fc8bda7dbe604ef94aabd769bfb0a26bbbc/com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java#L354:20), it would probably be possible to adapt it for Scala. The main difficulty lies in the fact that a Scala source file can generate many class files. If needed the `SourceLookUpProvider` can associate source files with class files and vice-versa.

Ok, Thanks for your help,  I'm a  newbie for Scala . But i  will do it when I have free time .

**Comment by lervag** [comment]
I'm curious: is there a specification of the hot code replace-feature anywhere? I've tried to search for this, but it seems to be a custom extension of the DAP and I can't find any general specs for it.

**Comment by adpi2** [comment]
@levarg Our implementation is the same as https://github.com/microsoft/vscode-java-debug which does not seem to be documented anywhere.

Here is a basic description:
- recompile the project
- collect all classes that changed
- in each thread, if there is a frame in a changed class, unstack it (and all frames on top)
- ask the JVM to reload the changed classes: the spec of this depend on your JVM, most JVMs don't accept new methods in a class
- step into once

**Comment by lervag** [comment]
Thanks for the reply and info, @adpi2! Appreciated!
