### ISSUE TITLE
Timeout Exception when running tests from neovim

### ISSUE THREAD

**Issue by kimlai** [scalacenter/scala-debug-adapter#409]
**Metals** 0.11.12
**Build Server** sbt 1.8.2
**sbt-debug-adapter** 3.0.9

Hello,

While using `nvim-metals` to run my tests I get the following error:

```
"Could not start debuggee TestSuitesDebuggee(file:/...#my-project/Test, [Test com.foo.BarSpec : subclass(false, org.scalatest.Suite)]) due to: Operation timed out after 5 seconds"
```

Launching a main class does work however, as does running the tests using Bloop as my build server.

I get the following dap traces:

```
[Trace][05:15:22 PM] Sent request:
{
  "type": "request",
  "seq": 1,
  "command": "initialize",
  "arguments": {
    "clientId": "neovim",
    "clientname": "neovim",
    "adapterID": "nvim-dap",
    "pathFormat": "path",
    "columnsStartAt1": true,
    "linesStartAt1": true,
    "supportsRunInTerminalRequest": true,
    "supportsVariableType": true,
    "supportsProgressReporting": true,
    "supportsStartDebuggingRequest": true,
    "locale": "en_US.UTF-8"
  }
}
[Trace][05:15:27 PM] Received response:
{
  "type": "response",
  "seq": 1,
  "request_seq": 1,
  "command": "initialize",
  "success": true,
  "body": {
    "supportsConfigurationDoneRequest": true,
    "supportsHitConditionalBreakpoints": true,
    "supportsConditionalBreakpoints": true,
    "supportsEvaluateForHovers": false,
    "supportsCompletionsRequest": true,
    "supportsRestartFrame": true,
    "supportsSetVariable": true,
    "supportsRestartRequest": false,
    "supportTerminateDebuggee": true,
    "supportsDelayedStackTraceLoading": false,
    "supportsLogPoints": true,
    "supportsExceptionInfoRequest": true,
    "exceptionBreakpointFilters": [
        "filter": "uncaught"
        "label": "Uncaught Exceptions",
        "filter": "uncaught"
      },
      {
        "label": "Caught Exceptions",
        "filter": "caught"
      }
    ],
    "supportsDataBreakpoints": true,
    "supportsClipboardContext": true
  }
}
[Trace][05:15:27 PM] Sent request:
{
  "type": "request",
  "seq": 2,
  "command": "launch",
  "arguments": {
    "type": "scala",
    "name": "RunOrTest",
    "request": "launch"
  }
}
[Trace][05:15:32 PM] Received response:
{
  "type": "response",
  "seq": 2,
  "request_seq": 2,
  "command": "launch",
  "success": false,
  "message": "Could not start debuggee TestSuitesDebuggee(file:/...#my-project/Test, [Test com.foo.BarSpec : subclass(false, org.scalatest.Suite)]) due to: Operation timed out after 5 seconds"
}
```

MetalsDoctor gives me this:
```
  - target type: Scala 2.13.10
  - compilation: ✅ 
  - diagnostics: ✅ 
  - interactive: ✅ 
  - semanticdb: ✅ 
  - debugging: ✅ 
  - java: ⚠️ 
```

I believe the error comes from [this timeout](https://github.com/scalacenter/scala-debug-adapter/blob/main/modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugSession.scala#L151), but I can't figure out why it happens. I tried using the master versions of both metals and sbt-debug-adapter and I get the same result.

**Comment by adpi2** [comment]
Thanks @kimlai for the detailed bug report.

It seems that the debuggee process failed to start but it is weird that we don't get any `stderr` event in the DAP traces. As if the process did not start at all. Or maybe it started but did not print anything to the console.

Does it happen in a single project or many of them? Can you share it so that we can reproduce the bug? Or can you minimize it?

What's your Java version? What's your `javaOptions` in your build: ```sbt show my-project/Test/javaOptions```?

**Comment by kimlai** [comment]
Hi @adpi2,

> Does it happen in a single project or many of them?

It happens on at least 2, but they have a very similar configuration.

> Can you share it so that we can reproduce the bug? Or can you minimize it?

Unfortunately those are private repositories, I can try to create a minimal project to reproduce it but I'm pretty new to Scala and sbt so I'm not sure I'll have the time (I did confirm that everything was ok on the basic [scalatest template ](https://github.com/scala/scalatest-example.g8)).

> What's your Java version? 

```shell
$ cs java --installed
adopt:1.11 installed at /Users/kimlai/Library/Caches/Coursier/arc/https/github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%252B28/OpenJDK11-jdk_x64_mac_hotspot_11_28.tar.gz/jdk-11+28/Contents/Home
```

> What's your `javaOptions` in your build: `sbt show my-project/Test/javaOptions`?

Looks like the project is not using any:
```
[info] List()
```

Is there else anything that I can do to try to get more logs/information, maybe modify some parts of this project and use the modified version locally?

**Comment by kimlai** [comment]
Not sure if it can help but I also got this trace from `.metals/bsp.trace.json`:

```
[Trace - 03:51:16 PM] Received response 'debugSession/start - (22)' in 881ms
Result: {
  "uri": "tcp://0.0.0.0:59352"
}
Error: null


[Trace - 03:51:16 PM] Received notification 'build/logMessage'
Params: {
  "type": 2,
  "message": "Found duplicate entry refined_2.13 in debuggee TestSuitesDebuggee(file:/Users/kimlai/my-project/#root/Test, [Test foo.BarSpec : subclass(false, org.scalatest.Suite)])"
}


[Trace - 03:51:16 PM] Received notification 'build/logMessage'
Params: {
  "type": 2,
  "message": "Found duplicate entry jackson-core in debuggee TestSuitesDebuggee(file:/Users/kimlai/my-project/#root/Test, [Test foo.BarSpec : subclass(false, org.scalatest.Suite)])"
}


[Trace - 03:51:18 PM] Received notification 'build/logMessage'
Params: {
  "type": 3,
  "message": "Configured debugger context in 1 second"
}
```

**Comment by kimlai** [comment]
Ok I tried removing the line at `BestmilePlugin.scala:23` and it does solve the problem. This is an internal sbt plugin so I'll close this issue and try to figure out why the offensive line makes the debugger fail.

Thanks a lot for your help! Maybe the additional logs could actually make their way to `main`, it would have helped a bunch :)
