### ISSUE TITLE
Failed evaluation in dotty

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#425]
In dotty `dotty.tools.dotc.rewrites.Rewrites.scala`, evaluation of `pbuf(2).span` fails with:
```
IllegalArgumentException@5626 "java.lang.IllegalArgumentException: object is not an instance of declaring class"
```

**Comment by iusildra** [comment]
Minimized code:
```scala
object Rewrites {
  private class Patch(val span: Span)
  
  def main(args: Array[String]): Unit = {
    val patch = Patch(Span(0))
    println("ok")
  }
}

class Span(start: Int) extends AnyVal
```
The problem seems to be with private classes AND classes extending AnyVal

**Comment by iusildra** [comment]
Hum, I'm trying to print the trees generated by the compiler, but even when passing `-Xprint:type` in `scalacOptions` to `DebugTools#loadExpressionCompiler`, the trees are not printed...
So I compile the minimized code in a separate file, but could not find any difference between the `private class Patch` and `class Patch` versions, each with and without a `val expr$19744 = patch.span` after the `val patch = ...`, apart from a different ordering, but I don't thing it matters

**Comment by adpi2** [comment]
I think the `IllegalArgumentException` comes from one of the method in https://github.com/scalacenter/scala-debug-adapter/blob/33e82725de8de1334377e9336de1a52475249591/modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala#L30-L113

You should be able to get the stack trace of this exception by inspecting it in the debug console or by wrapping the debug console in a `try catch`. Then you can add println in the methods in https://github.com/scalacenter/scala-debug-adapter/blob/33e82725de8de1334377e9336de1a52475249591/modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala#L30-L113 to get some info.

**Comment by iusildra** [comment]
Here's what I get when try-catching in the debug console :upside_down_face: 
```scala
$ try { patch.span } catch { case e => e.getStackTrace() }
> 0
$ patch.span
> IllegalArgumentException@1232 "java.lang.IllegalArgumentException: object is not an instance of declaring class"
$ try { patch.span } catch { case e => println(e.getStackTrace()) }
> 0
```

**Comment by adpi2** [comment]
Huh that's weird.

**Comment by iusildra** [comment]
Yes
