### ISSUE TITLE
apply() methods with runtime evaluator

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#452]
### Context
Whenever there is an method call, the runtime evaluator will search in order:
1. For an apply on a **module** or **class** (e.g. `Foo(42)`)
2. For a method of the same name
3. For an apply call shadowed by another method (e.g. `foo()`, where `foo` returns a `Foo$`)
4. Repeat in the outer class, if the `$outer` field is present

### Problem
Other 'implicit' `apply()` methods aren't handled, particularly for functional collections which elements can be accessed with an `apply()` method

```[tasklist]
### Tasks
- [x] Add support for these methods (idea: generalize the current `validateApplyCall` & `validateImplicitApplyCall` methods on `RuntimeDefaultValidator`)
- [x] Translate the `apply` call on `Array` with specific getter
```

**Comment by adpi2** [comment]
> Other 'implicit' apply() methods aren't handled, particularly for functional collections which elements can be accessed with an apply() method

All Scala collections should have a declared `apply` method in their class. Probably only the `Array` is problematic and should be handled differently.

(As a side note, it would be worth testing that we can access the elements of a tuple with `foo._1` or with `foo(0)`, and make another special handle for them, if needed).

**Comment by iusildra** [comment]
What I meant by 'implicit' apply call is when it is not explicitly called, e.g. `array(2)`
It might not be the best naming though
