### ISSUE TITLE
Add support for Java static field in expression compiler

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#462]

**Comment by iusildra** [comment]
That seems to work already. Given this java class
```java
package example;
public class JavaThing {
	public static int foo() { return 1; }
}
```
If I run this scala code
```scala
package example
object Main {
  def main(args: Array[String]): Unit =
    JavaThing.foo
}
```
I can write `List(1, 2, 3).map(_ => JavaThing.foo)` (to be sure that the runtime evaluator don't evaluate it) in the debug console and I obtain `List(1, 1, 1)`.
Did I miss something ?

**Comment by adpi2** [comment]
> Did I miss something ?

If was going to say, what if it is private? But if it is private then we cannot evaluate it.

Can a static field be protected?

```java
package example;
public class JavaThing {
	protected static int foo() { return 1; }
}
```

```scala
package example
object Main extends JavaThing {
  def main(args: Array[String]): Unit =
    JavaThing.foo
}
```

> (to be sure that the runtime evaluator don't evaluate it) 

That's smart!

**Comment by adpi2** [comment]
So yes a static field can be protected and its evaluation fails with:
```
NoSuchFieldException@757 "java.lang.NoSuchFieldException: $outer"
```
