### ISSUE TITLE
Pre-evaluation for methods

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#497]
Actually, among all the node of `RuntimeTree`, only those that can be evaluated by reading a value (`InstanceFieldTree`, `TopLevelModuleTree`...) can be pre-evaluated. Methods cannot for safety reasons.

But what if, once the validation is done and the evaluation started, the value's type returned by a method call would differ from the expected type ? We could revalidate the expression to access more precise members. For instance

```scala
class A
class B extends A { val b = "b" }

def test: A  = new B

test.b // could return "b"
```

**Comment by adpi2** [comment]
> But what if, once the validation is done and the evaluation started, the value's type returned by a method call would differ from the expected type ? We could revalidate the expression to access more precise members. For instance

How would that be useful? It is valid it can already be evaluated and all evaluations should return the same result.

**Comment by adpi2** [comment]
> once the validation is done and the evaluation started

If you cant prove that the expression is correct, why would you start the evaluation ? There is a risk that the method has side effect and that the expression still cannot be validated on the more precise type.

**Comment by iusildra** [comment]
True, I think I achieve to confuse myself :grinning:
