### ISSUE TITLE
Recurrent timeout on CI

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#501]
Since a few weeks the `windows-latest -- adoptium:1.17` regularly crashes during scripted tests, resulting in a CI run running for 5h (it happens only on this one)

**Comment by adpi2** [comment]
Where does it crash? Do we have a stack trace or error message?

**Comment by iusildra** [comment]
[CI run](https://github.com/scalacenter/scala-debug-adapter/actions/runs/5518288710/jobs/10062033947)
