### ISSUE TITLE
Recursive definition

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#523]
While looking at #427, I found an infinite-recursive (so it seems)
```scala
$ val (one, two) = (1, 2)
> BoxedUnit@284 "()"
     serialVersionUID: 8405543498931817370
     TYPE: Class (void)@325 "void"
     UNIT: BoxedUnit@284 "()"
```
I don't know if it's expected or not

**Comment by adpi2** [comment]
What do you mean by a infinite recursive? It seems the expression compiler returned a value "()" so I don't see where is the infinite recursion.

**Comment by iusildra** [comment]
I can unwrap the `UNIT`  and it shows the exact same thing with a `UNIT` that can be unwrap and so on and so forth

**Comment by adpi2** [comment]
Yep that seems to be the expected output because that's how BoxedUnit is defined.

Similarly I can have:
```scala
class Foo {
  val foo: Foo = this
}
```
