### ISSUE TITLE
Debugging very slow to start

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/scala-debug-adapter#541]
When trying to debug [this test](https://github.com/scalacenter/gradle-bloop/blob/1490802fcfbadaf856cd4957e97d490041b2e191/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala#L31) using Bloop/Metals/VSCode/Windows, I find the debugger very slow to start (> 5 mins)

This is mainly because of https://github.com/scalacenter/scala-debug-adapter/blob/faccb7f7810903ae1c37ee97f87e897d84340b50/modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala#L236

It's being hit many times on the gradle 5.0 jar: https://repo1.maven.org/maven2/dev/gradleplugins/gradle-api/5.0/

The Gradle jar and its sources are pretty busy (>3K folders, >12K files) and source files often don't exist for the corresponding class file.

The only class that I've been able to pin down as constantly being searched for is `package-info.class`/`package-info.java`.  Can this just be excluded from this area of code?  AFAIK - there's never any runnable code in these files.

Another possible performance improvement could be to group these missing files by `jar` and then scan for all of them instead of opening/closing the jar FS for every class file.

**Comment by adpi2** [comment]
Thanks for reporting this issue, starting the investigation and providing such level of details. I am taking a look.
