### ISSUE TITLE
Add configuration to enable/disable step filters

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#561]
We currently have 3 step filters:
- the runtime step filter
- the classloading step filter
- the Scala step filter

The idea is to add configuration in Metals settings to enable or disable them.

After that, we can add more step filters that are disabled by default but could be enabled by the user: for instance the implicit conversions, the using parameters...

**Comment by iusildra** [comment]
Wouldn't it be better to enable/disable them in `build.sbt` so it can be done by projects instead of by workspace ?

**Comment by adpi2** [comment]
> Wouldn't it be better to enable/disable them in build.sbt so it can be done by projects instead of by workspace ?

I don't think so because:
- `sbt-debug-adapter` is added by Metals not by the user and it is generally not committed to the repo.
- the debugger configuration is user-specific: 2 users working on the same repo can decide to use a different configuration.
- A project should not be tied to a specific IDE. I should not have Metals specific settings in the build.sbt if I use IntelliJ.
