### ISSUE TITLE
Hot code replace not reloading new classes

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#567]
When hot reloading after adding a new object `object Test { val test = "test" }`, the changes are not directly available, we need to modify it and reload again for it to be detected as "changed".

I suspect that it's because we return only loaded classes in `HotCodeReplaceProvider#redefineClasses`

**Comment by adpi2** [comment]
Don't we have a test that introduces a new class already?

**Comment by adpi2** [comment]
> vs code does not receive them

What does that mean? Does it mean that we cannot see the reloaded source file in VSCode if we step into it?
