### ISSUE TITLE
3.1.5 version not available on Maven Central

### ISSUE THREAD

**Issue by filipwiech** [scalacenter/scala-debug-adapter#618]
The 3.1.5 was tagged and released last week (over a week ago), but it looks like it's still not available on Maven Central. Maybe some publishing step has gone wrong? I noticed this because I was waiting for Scala Steward bot to pick it up in the Metals repository, but it hasn't happened so far. :thinking:

**Comment by adpi2** [comment]
Thanks for the report, I'll try to publish it again today!

**Comment by adpi2** [comment]
In progress: https://github.com/scalacenter/scala-debug-adapter/actions/runs/7044265993

**Comment by filipwiech** [comment]
Thank you! :+1: Although looking at the logs from the linked GitHub action it seems that artifacts were published to the Sonatype snapshot repository and with a `0.0.0+1-b6dadc54-SNAPSHOT` version? Not sure, but it appears that the publishing job has used the `main` branch? :slightly_smiling_face:

**Comment by adpi2** [comment]
> Not sure, but it appears that the publishing job has used the main branch? 🙂

Oh my goodness, it seems you're right :face_exhaling: 

Let's try it again: https://github.com/scalacenter/scala-debug-adapter/actions/runs/7046648490

Thanks for catching this.

**Comment by filipwiech** [comment]
The artifacts are now live on Maven Central, thank you so much! :ok_hand:

**Comment by adpi2** [comment]
> Looks like we are missing it for 2.13.12? https://repo1.maven.org/maven2/ch/epfl/scala/scala-expression-compiler_2.13.12/3.1.5/

I triggered a release for `2.13.12` in https://github.com/scalacenter/scala-debug-adapter/actions/runs/7084327432

> Btw. would it make sense to set expression eval for older versions to static. For example not release for 2.13.5 and set the version to last one that was released?

That's an interesting idea. But it is going to freeze the API. Or we would need 2 interfaces, one for the older versions and one for the newer. I'll think about it.
