### ISSUE TITLE
Expression evaluator can't find captured variables

### ISSUE THREAD

**Issue by rochala** [scalacenter/scala-debug-adapter#665]
1. presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSuite.memeber
2. set breakpoint at: https://github.com/lampepfl/dotty/blob/69170d3260a4f5989b63527192b245e4c57d8c3e/compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala#L182
3. Try to evaluate `tp` in expression evaluator

**Comment by adpi2** [comment]
I can reproduce that bug on any by-name argument:

```
object Main:
  def main(args: Array[String]): Unit =
    foo("hello")

  def foo(msg: String): String = bar {
    msg // evaluating msg throws NoSuchElementException
  }

  def bar(msg: => String): String = msg
```
