### ISSUE TITLE
Conditional breakpoints stop at wrong predicate after a period of time

### ISSUE THREAD

**Issue by rochala** [scalacenter/scala-debug-adapter#672]
It seems like conditional breakpoints are not working as intended.

I tried to debug a specific case which I wanted to find via a simple comparison of local variable against a string.

Reproduction:
1. Open file and add conditonal breakpoint here: [unpickleScalaFlags](https://github.com/rochala/dotty/blob/4733fbff1bce507d4ea541985939dbfca5ecfa2b/compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala#L442)

2. The condition should be `name.toString == "DelayedLazyVal"`
3. Try to debug test [local1](https://github.com/rochala/dotty/blob/4733fbff1bce507d4ea541985939dbfca5ecfa2b/presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSuite.scala#L461)

You will see that the first match was at:
<img width="515" alt="image" src="https://github.com/scalacenter/scala-debug-adapter/assets/48657087/4b0aab9f-2063-4861-b4ab-8419687ad0ac">

From this point conditional breakpoint will stop working.
The fix is to disable and then enable it, but it will stop on another wrong name after a few seconds.

This happened on scala dap 4.0.1

**Comment by adpi2** [comment]
Thanks for the report!

**Comment by adpi2** [comment]
Do you have any error in Metals log before you hit the conditional breakpoint?

**Comment by adpi2** [comment]
I reproduce it and I have:
```
2024.02.26 13:59:14 ERROR com.sun.jdi.ObjectCollectedException
```
