### ISSUE TITLE
Please publish the expression compiler for Scala 3.3.5-RC1

### ISSUE THREAD

**Issue by vasilmkd** [scalacenter/scala-debug-adapter#808]
Thanks in advance!

**Comment by adpi2** [comment]
Do you need a specific version of the expression compiler or any version?

**Comment by adpi2** [comment]
It is in progress: https://github.com/scalacenter/scala-debug-adapter/actions/runs/12271876895

FYI, releasing the expression compiler is part of the official release process. See for instance the tracker of 3.3.5-RC1: https://github.com/scala/scala3/issues/22169

**Comment by vasilmkd** [comment]
The publish job hasn't completed in 3 hours. Maybe a restart will help.

**Comment by adpi2** [comment]
It passed ! After 5 hours :)

Here is the artifact: https://repo1.maven.org/maven2/ch/epfl/scala/scala-expression-compiler_3.3.5-RC1/
